/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vistaescritorio;

import javax.swing.JFrame;

/**
 *
 * @author juanr
 */
public class VistaMain extends javax.swing.JFrame {

    /**
     * Creates new form VistaMain
     */
    public VistaMain() {
        initComponents();
        pack();                      
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUniversidad = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnSistemaClientes = new javax.swing.JButton();
        btnGestorDocumentos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnUniversidad.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnUniversidad.setText("Universidad");
        btnUniversidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUniversidadActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccione un servicio:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BtnSistemaClientes.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BtnSistemaClientes.setText("Sistema Clientes");
        BtnSistemaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSistemaClientesActionPerformed(evt);
            }
        });

        btnGestorDocumentos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnGestorDocumentos.setText("Gestor Documentos");
        btnGestorDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestorDocumentosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUniversidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnSistemaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestorDocumentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(btnUniversidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnSistemaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGestorDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestorDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestorDocumentosActionPerformed
         // 1. Crea un nuevo JFrame
        JFrame frame = new JFrame("Gestor Documentos");

        // 2. Ajusta su contenido para que sea tu JPanel
        frame.setContentPane(new VistaGestorDocumentos());

        // 3. Opcional: Ajusta comportamiento de cierre, tamaño, posición
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        frame.pack();
        frame.setLocationRelativeTo(null); // Para centrar la ventana

        // 4. Haz visible la nueva ventana
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestorDocumentosActionPerformed

    private void BtnSistemaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSistemaClientesActionPerformed
             // 1. Crea un nuevo JFrame
        JFrame frame = new JFrame("Sistema de clientes");

        // 2. Ajusta su contenido para que sea tu JPanel
        frame.setContentPane(new VistaCrudSistemaClientes());

        // 3. Opcional: Ajusta comportamiento de cierre, tamaño, posición
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        frame.pack();
        frame.setLocationRelativeTo(null); // Para centrar la ventana

        // 4. Haz visible la nueva ventana
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnSistemaClientesActionPerformed

    private void btnUniversidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUniversidadActionPerformed
          // 1. Crea un nuevo JFrame
        JFrame frame = new JFrame("Gestor Universidad");

        // 2. Ajusta su contenido para que sea tu JPanel
        frame.setContentPane(new VistaUniversidad());

        // 3. Opcional: Ajusta comportamiento de cierre, tamaño, posición
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        frame.pack();
        frame.setLocationRelativeTo(null); // Para centrar la ventana

        // 4. Haz visible la nueva ventana
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUniversidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSistemaClientes;
    private javax.swing.JButton btnGestorDocumentos;
    private javax.swing.JButton btnUniversidad;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
