/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.vistaescritorio;

import javax.swing.JFrame;

/**
 *
 * @author juanr
 */
public class VistaUniversidad extends javax.swing.JPanel {

    /**
     * Creates new form VistaGestorDocumentos
     */
    public VistaUniversidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnFacultad = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnCarrera = new javax.swing.JButton();
        BtnEstudiantes = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();

        BtnFacultad.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BtnFacultad.setText("FACULTAD");
        BtnFacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFacultadActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccione una entidad:");

        BtnCarrera.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BtnCarrera.setText("CARRERA");
        BtnCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCarreraActionPerformed(evt);
            }
        });

        BtnEstudiantes.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BtnEstudiantes.setText("ESTUDIANTES");
        BtnEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEstudiantesActionPerformed(evt);
            }
        });

        BtnVolver.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(BtnVolver)
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnFacultad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnEstudiantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(BtnFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnFacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFacultadActionPerformed
        
        JFrame frame = new JFrame("Crud Facultad");

        // 2. Ajusta su contenido para que sea tu JPanel
        frame.setContentPane(new VistaCrudFacultad());

        // 3. Opcional: Ajusta comportamiento de cierre, tamaño, posición
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        frame.pack();
        frame.setLocationRelativeTo(null); 

        // 4. Haz visible la nueva ventana
        frame.setVisible(true);
        JFrame topFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (topFrame != null) {
            topFrame.dispose();
        }
    }//GEN-LAST:event_BtnFacultadActionPerformed

    private void BtnCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCarreraActionPerformed
         JFrame frame = new JFrame("Crud Carrera");

        // 2. Ajusta su contenido para que sea tu JPanel
        frame.setContentPane(new VistaCrudCarrera());

        // 3. Opcional: Ajusta comportamiento de cierre, tamaño, posición
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        frame.pack();
        frame.setLocationRelativeTo(null); 

        // 4. Haz visible la nueva ventana
        frame.setVisible(true);
        JFrame topFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (topFrame != null) {
            topFrame.dispose();
        }
    }//GEN-LAST:event_BtnCarreraActionPerformed

    private void BtnEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEstudiantesActionPerformed
         JFrame frame = new JFrame("Crud Estudiantes");

        // 2. Ajusta su contenido para que sea tu JPanel
        frame.setContentPane(new VistaCrudEstudiantes());

        // 3. Opcional: Ajusta comportamiento de cierre, tamaño, posición
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        frame.pack();
        frame.setLocationRelativeTo(null); 

        // 4. Haz visible la nueva ventana
        frame.setVisible(true);
        JFrame topFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (topFrame != null) {
            topFrame.dispose();
        }
        
    }//GEN-LAST:event_BtnEstudiantesActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        

        new VistaMain().setVisible(true);

        // Obtén la ventana contenedora actual (donde está este JPanel) y ciérrala
        JFrame topFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (topFrame != null) {
            topFrame.dispose();
        }

    }//GEN-LAST:event_BtnVolverActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCarrera;
    private javax.swing.JButton BtnEstudiantes;
    private javax.swing.JButton BtnFacultad;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
