/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.vistaescritorio;

import javax.swing.JFrame;

/**
 *
 * @author juanr
 */
public class VistaGestorDocumentos extends javax.swing.JPanel {

    /**
     * Creates new form VistaGestorDocumentos
     */
    public VistaGestorDocumentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnPDF = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnHTML = new javax.swing.JButton();
        BtnTextoPlano = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();

        BtnPDF.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BtnPDF.setText("PDF");
        BtnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPDFActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Seleccione un tipo de documento:");

        BtnHTML.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BtnHTML.setText("HTML");
        BtnHTML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHTMLActionPerformed(evt);
            }
        });

        BtnTextoPlano.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BtnTextoPlano.setText("TEXTO PLANO");
        BtnTextoPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTextoPlanoActionPerformed(evt);
            }
        });

        BtnVolver.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnHTML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnTextoPlano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnVolver)
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(BtnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnHTML, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnTextoPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPDFActionPerformed
        abrirVistaMostrarDocumento("PDF");
    }//GEN-LAST:event_BtnPDFActionPerformed

    private void BtnHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHTMLActionPerformed
        abrirVistaMostrarDocumento("HTML");
    }//GEN-LAST:event_BtnHTMLActionPerformed

    private void BtnTextoPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTextoPlanoActionPerformed
        abrirVistaMostrarDocumento("TEXTO_PLANO");
        
    }//GEN-LAST:event_BtnTextoPlanoActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        

        new VistaMain().setVisible(true);

        // Obtén la ventana contenedora actual (donde está este JPanel) y ciérrala
        JFrame topFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (topFrame != null) {
            topFrame.dispose();
        }

    }//GEN-LAST:event_BtnVolverActionPerformed
    
    private void abrirVistaMostrarDocumento(String tipoDocumento) {
        
         JFrame frame = new JFrame("Mostrar Documento " + tipoDocumento);

        // 2. Ajusta su contenido para que sea tu JPanel
        frame.setContentPane(new VistaMostrarDocumento(tipoDocumento));

        // 3. Opcional: Ajusta comportamiento de cierre, tamaño, posición
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        frame.pack();
        frame.setLocationRelativeTo(null); 

        // 4. Haz visible la nueva ventana
        frame.setVisible(true);
        JFrame topFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (topFrame != null) {
            topFrame.dispose();
        }
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHTML;
    private javax.swing.JButton BtnPDF;
    private javax.swing.JButton BtnTextoPlano;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
